{ pkgs, pkgsUnstable, system, inputs, ... }:
{
    home.packages = with pkgs; [
        pkgsUnstable.jetbrains.idea-ultimate
        sshfs
        fastfetch
        keepassxc
        filezilla
        gnomeExtensions.forge
        gnomeExtensions.app-icons-taskbar
        youtube-music
        vscode-fhs
        openssh
        wezterm
        devpod
        jetbrains.gateway
        go
        solaar
        remmina
        ripgrep
        binutils
        kubectl
        playerctl
        parted
        pavucontrol
        pkgsUnstable.talosctl
        hardinfo2
        kubernetes-helm
        mangohud
        cookiecutter
        usbimager
        pinta
        libreoffice
        blueberry
        realvnc-vnc-viewer
        vial
        inputs.dagger.packages.${system}.dagger
        fluxcd
        sops
        gnupg
        age
    ];
}

